[project]
name = "iograph"
version = "2.0.4"
description = "<source media=\"(prefers-color-scheme: dark)\" srcset=\"iograph-2.0.0-dark.jpg\">"
readme = "README.md"
requires-python = ">=3.9.13"
authors = [
    { name = "Pho Hale", email = "CommanderPho@users.noreply.github.com" },
]
dependencies = [
    "phopylslhelper",
    "pillow>=10.4.0",
    "pyinstaller>=6.21.0",
    "PyQt6>=6.7.0",
]

[tool.uv.sources]
phopylslhelper = { path = "../PhoPyLSLhelper", editable = true }
